DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS shares;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS recording_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS recordings;
DROP TABLE IF EXISTS users;
